export const FETCH_USER = "FETCH_USER";
export const ACTIVE_ACTION_DROPDOWN = "ACTIVE_ACTION_DROPDOWN";
export const ON_MODAL_TITLE_CHANGE = "ON_MODAL_TITLE_CHANGE";
export const ON_MODAL_DESC_CHANGE = "ON_MODAL_DESC_CHANGE";
export const CREATE_FOLDER = "CREATE_FOLDER";
